Traceback (most recent call last):
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
draws = dist_pareto.rvs(N, random_state=0)
tax = np.vectorize(h)(draws, a=0.05, b=0.1, w_bar=2.5)
T_hat = np.sum(tax)
T_hat
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[12], line 2[0m
[1;32m      1[0m draws [38;5;241m=[39m dist_pareto[38;5;241m.[39mrvs(N, random_state[38;5;241m=[39m[38;5;241m0[39m)
[0;32m----> 2[0m tax [38;5;241m=[39m np[38;5;241m.[39mvectorize([43mh[49m)(draws, a[38;5;241m=[39m[38;5;241m0.05[39m, b[38;5;241m=[39m[38;5;241m0.1[39m, w_bar[38;5;241m=[39m[38;5;241m2.5[39m)
[1;32m      3[0m T_hat [38;5;241m=[39m np[38;5;241m.[39msum(tax)
[1;32m      4[0m T_hat

[0;31mNameError[0m: name 'h' is not defined
NameError: name 'h' is not defined

